version: 0.1
phases:
    install:
        commands:
            - echo installing Node JS...
            - npm install
    pre_build:
        commands:
            - echo Pre_Build started...
            - echo Pre_Build end...
    build:
        commands:
            - echo Build started...
            - echo Build ended...
cache:
  paths:
    - './node_modules/**/*'            
            